// Code generated by protoc-gen-twirp v5.2.0, DO NOT EDIT.
// source: signals.proto

/*
Package signals is a generated twirp stub package.
This code was generated with github.com/twitchtv/twirp/protoc-gen-twirp v5.2.0.

It is generated from these files:
	signals.proto
*/
package signals

import bytes "bytes"
import strings "strings"
import context "context"
import fmt "fmt"
import ioutil "io/ioutil"
import log "log"
import http "net/http"

import jsonpb "github.com/golang/protobuf/jsonpb"
import proto "github.com/golang/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Imports only used by utility functions:
import io "io"
import strconv "strconv"
import json "encoding/json"
import url "net/url"

// ===================================
// BusierThanChannelsService Interface
// ===================================

type BusierThanChannelsService interface {
	BusierThanChannels(context.Context, *BusierThanChannelsRequest) (*BusierThanChannelsResponse, error)
}

// =========================================
// BusierThanChannelsService Protobuf Client
// =========================================

type busierThanChannelsServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewBusierThanChannelsServiceProtobufClient creates a Protobuf client that implements the BusierThanChannelsService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewBusierThanChannelsServiceProtobufClient(addr string, client HTTPClient) BusierThanChannelsService {
	prefix := urlBase(addr) + BusierThanChannelsServicePathPrefix
	urls := [1]string{
		prefix + "BusierThanChannels",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &busierThanChannelsServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &busierThanChannelsServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *busierThanChannelsServiceProtobufClient) BusierThanChannels(ctx context.Context, in *BusierThanChannelsRequest) (*BusierThanChannelsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "signals")
	ctx = ctxsetters.WithServiceName(ctx, "BusierThanChannelsService")
	ctx = ctxsetters.WithMethodName(ctx, "BusierThanChannels")
	out := new(BusierThanChannelsResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =====================================
// BusierThanChannelsService JSON Client
// =====================================

type busierThanChannelsServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewBusierThanChannelsServiceJSONClient creates a JSON client that implements the BusierThanChannelsService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewBusierThanChannelsServiceJSONClient(addr string, client HTTPClient) BusierThanChannelsService {
	prefix := urlBase(addr) + BusierThanChannelsServicePathPrefix
	urls := [1]string{
		prefix + "BusierThanChannels",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &busierThanChannelsServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &busierThanChannelsServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *busierThanChannelsServiceJSONClient) BusierThanChannels(ctx context.Context, in *BusierThanChannelsRequest) (*BusierThanChannelsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "signals")
	ctx = ctxsetters.WithServiceName(ctx, "BusierThanChannelsService")
	ctx = ctxsetters.WithMethodName(ctx, "BusierThanChannels")
	out := new(BusierThanChannelsResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ========================================
// BusierThanChannelsService Server Handler
// ========================================

type busierThanChannelsServiceServer struct {
	BusierThanChannelsService
	hooks *twirp.ServerHooks
}

func NewBusierThanChannelsServiceServer(svc BusierThanChannelsService, hooks *twirp.ServerHooks) TwirpServer {
	return &busierThanChannelsServiceServer{
		BusierThanChannelsService: svc,
		hooks: hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *busierThanChannelsServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// BusierThanChannelsServicePathPrefix is used for all URL paths on a twirp BusierThanChannelsService server.
// Requests are always: POST BusierThanChannelsServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const BusierThanChannelsServicePathPrefix = "/twirp/signals.BusierThanChannelsService/"

func (s *busierThanChannelsServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "signals")
	ctx = ctxsetters.WithServiceName(ctx, "BusierThanChannelsService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/signals.BusierThanChannelsService/BusierThanChannels":
		s.serveBusierThanChannels(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *busierThanChannelsServiceServer) serveBusierThanChannels(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveBusierThanChannelsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveBusierThanChannelsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *busierThanChannelsServiceServer) serveBusierThanChannelsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "BusierThanChannels")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	reqContent := new(BusierThanChannelsRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BusierThanChannelsResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.BusierThanChannels(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BusierThanChannelsResponse and nil error while calling BusierThanChannels. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(buf.Bytes()); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *busierThanChannelsServiceServer) serveBusierThanChannelsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "BusierThanChannels")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(BusierThanChannelsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BusierThanChannelsResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.BusierThanChannels(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BusierThanChannelsResponse and nil error while calling BusierThanChannels. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(respBytes); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *busierThanChannelsServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 0
}

func (s *busierThanChannelsServiceServer) ProtocGenTwirpVersion() string {
	return "v5.2.0"
}

// ====================================
// QuieterThanChannelsService Interface
// ====================================

type QuieterThanChannelsService interface {
	QuieterThanChannels(context.Context, *QuieterThanChannelsRequest) (*QuieterThanChannelsResponse, error)
}

// ==========================================
// QuieterThanChannelsService Protobuf Client
// ==========================================

type quieterThanChannelsServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewQuieterThanChannelsServiceProtobufClient creates a Protobuf client that implements the QuieterThanChannelsService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewQuieterThanChannelsServiceProtobufClient(addr string, client HTTPClient) QuieterThanChannelsService {
	prefix := urlBase(addr) + QuieterThanChannelsServicePathPrefix
	urls := [1]string{
		prefix + "QuieterThanChannels",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &quieterThanChannelsServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &quieterThanChannelsServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *quieterThanChannelsServiceProtobufClient) QuieterThanChannels(ctx context.Context, in *QuieterThanChannelsRequest) (*QuieterThanChannelsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "signals")
	ctx = ctxsetters.WithServiceName(ctx, "QuieterThanChannelsService")
	ctx = ctxsetters.WithMethodName(ctx, "QuieterThanChannels")
	out := new(QuieterThanChannelsResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ======================================
// QuieterThanChannelsService JSON Client
// ======================================

type quieterThanChannelsServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewQuieterThanChannelsServiceJSONClient creates a JSON client that implements the QuieterThanChannelsService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewQuieterThanChannelsServiceJSONClient(addr string, client HTTPClient) QuieterThanChannelsService {
	prefix := urlBase(addr) + QuieterThanChannelsServicePathPrefix
	urls := [1]string{
		prefix + "QuieterThanChannels",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &quieterThanChannelsServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &quieterThanChannelsServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *quieterThanChannelsServiceJSONClient) QuieterThanChannels(ctx context.Context, in *QuieterThanChannelsRequest) (*QuieterThanChannelsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "signals")
	ctx = ctxsetters.WithServiceName(ctx, "QuieterThanChannelsService")
	ctx = ctxsetters.WithMethodName(ctx, "QuieterThanChannels")
	out := new(QuieterThanChannelsResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =========================================
// QuieterThanChannelsService Server Handler
// =========================================

type quieterThanChannelsServiceServer struct {
	QuieterThanChannelsService
	hooks *twirp.ServerHooks
}

func NewQuieterThanChannelsServiceServer(svc QuieterThanChannelsService, hooks *twirp.ServerHooks) TwirpServer {
	return &quieterThanChannelsServiceServer{
		QuieterThanChannelsService: svc,
		hooks: hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *quieterThanChannelsServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// QuieterThanChannelsServicePathPrefix is used for all URL paths on a twirp QuieterThanChannelsService server.
// Requests are always: POST QuieterThanChannelsServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const QuieterThanChannelsServicePathPrefix = "/twirp/signals.QuieterThanChannelsService/"

func (s *quieterThanChannelsServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "signals")
	ctx = ctxsetters.WithServiceName(ctx, "QuieterThanChannelsService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/signals.QuieterThanChannelsService/QuieterThanChannels":
		s.serveQuieterThanChannels(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *quieterThanChannelsServiceServer) serveQuieterThanChannels(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveQuieterThanChannelsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveQuieterThanChannelsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *quieterThanChannelsServiceServer) serveQuieterThanChannelsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "QuieterThanChannels")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	reqContent := new(QuieterThanChannelsRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *QuieterThanChannelsResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.QuieterThanChannels(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *QuieterThanChannelsResponse and nil error while calling QuieterThanChannels. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(buf.Bytes()); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quieterThanChannelsServiceServer) serveQuieterThanChannelsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "QuieterThanChannels")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(QuieterThanChannelsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *QuieterThanChannelsResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.QuieterThanChannels(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *QuieterThanChannelsResponse and nil error while calling QuieterThanChannels. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(respBytes); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quieterThanChannelsServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 1
}

func (s *quieterThanChannelsServiceServer) ProtocGenTwirpVersion() string {
	return "v5.2.0"
}

// ================================
// ChannelStrengthService Interface
// ================================

type ChannelStrengthService interface {
	ChannelStrength(context.Context, *ChannelStrengthRequest) (*ChannelStrengthResponse, error)
}

// ======================================
// ChannelStrengthService Protobuf Client
// ======================================

type channelStrengthServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewChannelStrengthServiceProtobufClient creates a Protobuf client that implements the ChannelStrengthService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewChannelStrengthServiceProtobufClient(addr string, client HTTPClient) ChannelStrengthService {
	prefix := urlBase(addr) + ChannelStrengthServicePathPrefix
	urls := [1]string{
		prefix + "ChannelStrength",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &channelStrengthServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &channelStrengthServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *channelStrengthServiceProtobufClient) ChannelStrength(ctx context.Context, in *ChannelStrengthRequest) (*ChannelStrengthResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "signals")
	ctx = ctxsetters.WithServiceName(ctx, "ChannelStrengthService")
	ctx = ctxsetters.WithMethodName(ctx, "ChannelStrength")
	out := new(ChannelStrengthResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==================================
// ChannelStrengthService JSON Client
// ==================================

type channelStrengthServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewChannelStrengthServiceJSONClient creates a JSON client that implements the ChannelStrengthService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewChannelStrengthServiceJSONClient(addr string, client HTTPClient) ChannelStrengthService {
	prefix := urlBase(addr) + ChannelStrengthServicePathPrefix
	urls := [1]string{
		prefix + "ChannelStrength",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &channelStrengthServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &channelStrengthServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *channelStrengthServiceJSONClient) ChannelStrength(ctx context.Context, in *ChannelStrengthRequest) (*ChannelStrengthResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "signals")
	ctx = ctxsetters.WithServiceName(ctx, "ChannelStrengthService")
	ctx = ctxsetters.WithMethodName(ctx, "ChannelStrength")
	out := new(ChannelStrengthResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =====================================
// ChannelStrengthService Server Handler
// =====================================

type channelStrengthServiceServer struct {
	ChannelStrengthService
	hooks *twirp.ServerHooks
}

func NewChannelStrengthServiceServer(svc ChannelStrengthService, hooks *twirp.ServerHooks) TwirpServer {
	return &channelStrengthServiceServer{
		ChannelStrengthService: svc,
		hooks: hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *channelStrengthServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// ChannelStrengthServicePathPrefix is used for all URL paths on a twirp ChannelStrengthService server.
// Requests are always: POST ChannelStrengthServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const ChannelStrengthServicePathPrefix = "/twirp/signals.ChannelStrengthService/"

func (s *channelStrengthServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "signals")
	ctx = ctxsetters.WithServiceName(ctx, "ChannelStrengthService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/signals.ChannelStrengthService/ChannelStrength":
		s.serveChannelStrength(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *channelStrengthServiceServer) serveChannelStrength(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveChannelStrengthJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveChannelStrengthProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *channelStrengthServiceServer) serveChannelStrengthJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ChannelStrength")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	reqContent := new(ChannelStrengthRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ChannelStrengthResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.ChannelStrength(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ChannelStrengthResponse and nil error while calling ChannelStrength. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(buf.Bytes()); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *channelStrengthServiceServer) serveChannelStrengthProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ChannelStrength")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(ChannelStrengthRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ChannelStrengthResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.ChannelStrength(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ChannelStrengthResponse and nil error while calling ChannelStrength. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(respBytes); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *channelStrengthServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 2
}

func (s *channelStrengthServiceServer) ProtocGenTwirpVersion() string {
	return "v5.2.0"
}

// =====
// Utils
// =====

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
//
// HTTPClient implementations should not follow redirects. Redirects are
// automatically disabled if *(net/http).Client is passed to client
// constructors. See the withoutRedirects function in this file for more
// details.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// TwirpServer is the interface generated server structs will support: they're
// HTTP handlers with additional methods for accessing metadata about the
// service. Those accessors are a low-level API for building reflection tools.
// Most people can think of TwirpServers as just http.Handlers.
type TwirpServer interface {
	http.Handler
	// ServiceDescriptor returns gzipped bytes describing the .proto file that
	// this service was generated from. Once unzipped, the bytes can be
	// unmarshalled as a
	// github.com/golang/protobuf/protoc-gen-go/descriptor.FileDescriptorProto.
	//
	// The returned integer is the index of this particular service within that
	// FileDescriptorProto's 'Service' slice of ServiceDescriptorProtos. This is a
	// low-level field, expected to be used for reflection.
	ServiceDescriptor() ([]byte, int)
	// ProtocGenTwirpVersion is the semantic version string of the version of
	// twirp used to generate this file.
	ProtocGenTwirpVersion() string
}

// WriteError writes an HTTP response with a valid Twirp error format.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func WriteError(resp http.ResponseWriter, err error) {
	writeError(context.Background(), resp, err, nil)
}

// writeError writes Twirp errors in the response and triggers hooks.
func writeError(ctx context.Context, resp http.ResponseWriter, err error, hooks *twirp.ServerHooks) {
	// Non-twirp errors are wrapped as Internal (default)
	twerr, ok := err.(twirp.Error)
	if !ok {
		twerr = twirp.InternalErrorWith(err)
	}

	statusCode := twirp.ServerHTTPStatusFromErrorCode(twerr.Code())
	ctx = ctxsetters.WithStatusCode(ctx, statusCode)
	ctx = callError(ctx, hooks, twerr)

	resp.Header().Set("Content-Type", "application/json") // Error responses are always JSON (instead of protobuf)
	resp.WriteHeader(statusCode)                          // HTTP response status code

	respBody := marshalErrorToJSON(twerr)
	_, err2 := resp.Write(respBody)
	if err2 != nil {
		log.Printf("unable to send error message %q: %s", twerr, err2)
	}

	callResponseSent(ctx, hooks)
}

// urlBase helps ensure that addr specifies a scheme. If it is unparsable
// as a URL, it returns addr unchanged.
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

// getCustomHTTPReqHeaders retrieves a copy of any headers that are set in
// a context through the twirp.WithHTTPRequestHeaders function.
// If there are no headers set, or if they have the wrong type, nil is returned.
func getCustomHTTPReqHeaders(ctx context.Context) http.Header {
	header, ok := twirp.HTTPRequestHeaders(ctx)
	if !ok || header == nil {
		return nil
	}
	copied := make(http.Header)
	for k, vv := range header {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}
	return copied
}

// closebody closes a response or request body and just logs
// any error encountered while closing, since errors are
// considered very unusual.
func closebody(body io.Closer) {
	if err := body.Close(); err != nil {
		log.Printf("error closing body: %q", err)
	}
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequest("POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if customHeader := getCustomHTTPReqHeaders(ctx); customHeader != nil {
		req.Header = customHeader
	}
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Twirp-Version", "v5.2.0")
	return req, nil
}

// JSON serialization for errors
type twerrJSON struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Meta map[string]string `json:"meta,omitempty"`
}

// marshalErrorToJSON returns JSON from a twirp.Error, that can be used as HTTP error response body.
// If serialization fails, it will use a descriptive Internal error instead.
func marshalErrorToJSON(twerr twirp.Error) []byte {
	// make sure that msg is not too large
	msg := twerr.Msg()
	if len(msg) > 1e6 {
		msg = msg[:1e6]
	}

	tj := twerrJSON{
		Code: string(twerr.Code()),
		Msg:  msg,
		Meta: twerr.MetaMap(),
	}

	buf, err := json.Marshal(&tj)
	if err != nil {
		buf = []byte("{\"type\": \"" + twirp.Internal + "\", \"msg\": \"There was an error but it could not be serialized into JSON\"}") // fallback
	}

	return buf
}

// errorFromResponse builds a twirp.Error from a non-200 HTTP response.
// If the response has a valid serialized Twirp error, then it's returned.
// If not, the response status code is used to generate a similar twirp
// error. See twirpErrorFromIntermediary for more info on intermediary errors.
func errorFromResponse(resp *http.Response) twirp.Error {
	statusCode := resp.StatusCode
	statusText := http.StatusText(statusCode)

	if isHTTPRedirect(statusCode) {
		// Unexpected redirect: it must be an error from an intermediary.
		// Twirp clients don't follow redirects automatically, Twirp only handles
		// POST requests, redirects should only happen on GET and HEAD requests.
		location := resp.Header.Get("Location")
		msg := fmt.Sprintf("unexpected HTTP status code %d %q received, Location=%q", statusCode, statusText, location)
		return twirpErrorFromIntermediary(statusCode, msg, location)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read server error response body", err)
	}
	var tj twerrJSON
	if err := json.Unmarshal(respBodyBytes, &tj); err != nil {
		// Invalid JSON response; it must be an error from an intermediary.
		msg := fmt.Sprintf("Error from intermediary with HTTP status code %d %q", statusCode, statusText)
		return twirpErrorFromIntermediary(statusCode, msg, string(respBodyBytes))
	}

	errorCode := twirp.ErrorCode(tj.Code)
	if !twirp.IsValidErrorCode(errorCode) {
		msg := "invalid type returned from server error response: " + tj.Code
		return twirp.InternalError(msg)
	}

	twerr := twirp.NewError(errorCode, tj.Msg)
	for k, v := range tj.Meta {
		twerr = twerr.WithMeta(k, v)
	}
	return twerr
}

// twirpErrorFromIntermediary maps HTTP errors from non-twirp sources to twirp errors.
// The mapping is similar to gRPC: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.
// Returned twirp Errors have some additional metadata for inspection.
func twirpErrorFromIntermediary(status int, msg string, bodyOrLocation string) twirp.Error {
	var code twirp.ErrorCode
	if isHTTPRedirect(status) { // 3xx
		code = twirp.Internal
	} else {
		switch status {
		case 400: // Bad Request
			code = twirp.Internal
		case 401: // Unauthorized
			code = twirp.Unauthenticated
		case 403: // Forbidden
			code = twirp.PermissionDenied
		case 404: // Not Found
			code = twirp.BadRoute
		case 429, 502, 503, 504: // Too Many Requests, Bad Gateway, Service Unavailable, Gateway Timeout
			code = twirp.Unavailable
		default: // All other codes
			code = twirp.Unknown
		}
	}

	twerr := twirp.NewError(code, msg)
	twerr = twerr.WithMeta("http_error_from_intermediary", "true") // to easily know if this error was from intermediary
	twerr = twerr.WithMeta("status_code", strconv.Itoa(status))
	if isHTTPRedirect(status) {
		twerr = twerr.WithMeta("location", bodyOrLocation)
	} else {
		twerr = twerr.WithMeta("body", bodyOrLocation)
	}
	return twerr
}
func isHTTPRedirect(status int) bool {
	return status >= 300 && status <= 399
}

// wrappedError implements the github.com/pkg/errors.Causer interface, allowing errors to be
// examined for their root cause.
type wrappedError struct {
	msg   string
	cause error
}

func wrapErr(err error, msg string) error { return &wrappedError{msg: msg, cause: err} }
func (e *wrappedError) Cause() error      { return e.cause }
func (e *wrappedError) Error() string     { return e.msg + ": " + e.cause.Error() }

// clientError adds consistency to errors generated in the client
func clientError(desc string, err error) twirp.Error {
	return twirp.InternalErrorWith(wrapErr(err, desc))
}

// badRouteError is used when the twirp server cannot route a request
func badRouteError(msg string, method, url string) twirp.Error {
	err := twirp.NewError(twirp.BadRoute, msg)
	err = err.WithMeta("twirp_invalid_route", method+" "+url)
	return err
}

// The standard library will, by default, redirect requests (including POSTs) if it gets a 302 or
// 303 response, and also 301s in go1.8. It redirects by making a second request, changing the
// method to GET and removing the body. This produces very confusing error messages, so instead we
// set a redirect policy that always errors. This stops Go from executing the redirect.
//
// We have to be a little careful in case the user-provided http.Client has its own CheckRedirect
// policy - if so, we'll run through that policy first.
//
// Because this requires modifying the http.Client, we make a new copy of the client and return it.
func withoutRedirects(in *http.Client) *http.Client {
	copy := *in
	copy.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if in.CheckRedirect != nil {
			// Run the input's redirect if it exists, in case it has side effects, but ignore any error it
			// returns, since we want to use ErrUseLastResponse.
			err := in.CheckRedirect(req, via)
			_ = err // Silly, but this makes sure generated code passes errcheck -blank, which some people use.
		}
		return http.ErrUseLastResponse
	}
	return &copy
}

// doProtobufRequest is common code to make a request to the remote twirp service.
func doProtobufRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBodyBytes, err := proto.Marshal(in)
	if err != nil {
		return clientError("failed to marshal proto request", err)
	}
	reqBody := bytes.NewBuffer(reqBodyBytes)
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/protobuf")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read response body", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if err = proto.Unmarshal(respBodyBytes, out); err != nil {
		return clientError("failed to unmarshal proto response", err)
	}
	return nil
}

// doJSONRequest is common code to make a request to the remote twirp service.
func doJSONRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBody := bytes.NewBuffer(nil)
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(reqBody, in); err != nil {
		return clientError("failed to marshal json request", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/json")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(resp.Body, out); err != nil {
		return clientError("failed to unmarshal json response", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}
	return nil
}

// Call twirp.ServerHooks.RequestReceived if the hook is available
func callRequestReceived(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestReceived == nil {
		return ctx, nil
	}
	return h.RequestReceived(ctx)
}

// Call twirp.ServerHooks.RequestRouted if the hook is available
func callRequestRouted(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestRouted == nil {
		return ctx, nil
	}
	return h.RequestRouted(ctx)
}

// Call twirp.ServerHooks.ResponsePrepared if the hook is available
func callResponsePrepared(ctx context.Context, h *twirp.ServerHooks) context.Context {
	if h == nil || h.ResponsePrepared == nil {
		return ctx
	}
	return h.ResponsePrepared(ctx)
}

// Call twirp.ServerHooks.ResponseSent if the hook is available
func callResponseSent(ctx context.Context, h *twirp.ServerHooks) {
	if h == nil || h.ResponseSent == nil {
		return
	}
	h.ResponseSent(ctx)
}

// Call twirp.ServerHooks.Error if the hook is available
func callError(ctx context.Context, h *twirp.ServerHooks, err twirp.Error) context.Context {
	if h == nil || h.Error == nil {
		return ctx
	}
	return h.Error(ctx, err)
}

var twirpFileDescriptor0 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x14, 0x64, 0x7f, 0x3f, 0x6c, 0xcb, 0x13, 0x11, 0x56, 0xa8, 0x71, 0x05, 0x2d, 0x5b, 0x0f, 0x05,
	0xa5, 0x87, 0x78, 0x54, 0x2f, 0x7a, 0xd0, 0x9b, 0x98, 0xf6, 0x2a, 0x98, 0xd6, 0xa5, 0x0d, 0xc4,
	0x4d, 0xba, 0x7f, 0x14, 0x3d, 0xf8, 0x69, 0xc4, 0xcf, 0x29, 0xa6, 0x6f, 0x63, 0x6d, 0xb6, 0xa1,
	0x07, 0x8f, 0x33, 0x9b, 0x79, 0xf3, 0x86, 0x79, 0x81, 0x2d, 0x9d, 0x4c, 0x64, 0x9c, 0xea, 0x7e,
	0xae, 0x32, 0x93, 0xd1, 0x26, 0x42, 0x7e, 0x06, 0x7b, 0x97, 0x56, 0x27, 0x42, 0x0d, 0xa7, 0xb1,
	0xbc, 0x9a, 0xc6, 0x52, 0x8a, 0x54, 0x47, 0x62, 0x66, 0x85, 0x36, 0xf4, 0x00, 0x20, 0xcd, 0x5e,
	0x84, 0x1a, 0x65, 0x56, 0x3e, 0x06, 0xa4, 0x43, 0x7a, 0x24, 0x5a, 0x60, 0xf8, 0x07, 0x01, 0xe6,
	0x53, 0xeb, 0x3c, 0x93, 0x5a, 0xd0, 0x6b, 0x68, 0x8d, 0x91, 0x0b, 0x48, 0xe7, 0x7f, 0x6f, 0x33,
	0x3c, 0xee, 0xbb, 0x35, 0x56, 0xcb, 0xfa, 0x48, 0x44, 0xa5, 0x98, 0x5d, 0x40, 0x13, 0x49, 0xda,
	0x86, 0x86, 0xb4, 0x4f, 0x23, 0xa1, 0x8a, 0x75, 0x36, 0x22, 0x44, 0x94, 0x41, 0x4b, 0x1b, 0x25,
	0xe4, 0xc4, 0x4c, 0x83, 0x7f, 0xc5, 0xa2, 0x25, 0xe6, 0xe7, 0xc0, 0xee, 0x6c, 0x22, 0xcc, 0xca,
	0x90, 0x36, 0xcf, 0x97, 0x42, 0xfe, 0x30, 0xfc, 0x93, 0xc0, 0xbe, 0x57, 0x8e, 0x29, 0x6f, 0x2a,
	0x29, 0x4f, 0xca, 0x94, 0x35, 0xba, 0xbf, 0x8f, 0x19, 0x42, 0x1b, 0xe5, 0x03, 0xa4, 0x5c, 0xc4,
	0x00, 0x9a, 0x68, 0x82, 0xe3, 0x1c, 0xe4, 0xb7, 0xb0, 0x5b, 0xd1, 0x60, 0xae, 0x45, 0x2b, 0xf2,
	0xdb, 0xea, 0x7b, 0xe0, 0xcc, 0xc6, 0x69, 0x62, 0x5e, 0x71, 0x0b, 0x07, 0xc3, 0x37, 0xdf, 0x3d,
	0x0d, 0x84, 0x7a, 0x4e, 0xc6, 0x82, 0xde, 0x03, 0xad, 0x3e, 0x52, 0x5e, 0x7b, 0x14, 0x45, 0x02,
	0xd6, 0x5d, 0xe3, 0x70, 0xc2, 0x77, 0x6f, 0xcf, 0xce, 0xfc, 0x01, 0x76, 0x3c, 0xaf, 0xb4, 0x5b,
	0x5f, 0xd6, 0xdc, 0xfe, 0x68, 0x9d, 0x46, 0x43, 0x59, 0x29, 0xc0, 0x79, 0x0f, 0x61, 0x7b, 0xe9,
	0x85, 0x1e, 0x96, 0x23, 0xfd, 0xa5, 0xb1, 0xce, 0xea, 0x0f, 0xe6, 0x7e, 0xa3, 0x46, 0xf1, 0x2f,
	0x9f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x26, 0xaa, 0x8d, 0xfe, 0xdc, 0x03, 0x00, 0x00,
}
