// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signals.proto

/*
Package signals is a generated protocol buffer package.

It is generated from these files:
	signals.proto

It has these top-level messages:
	BusierThanChannelsRequest
	BusierThanChannelsResponse
	QuieterThanChannelsRequest
	QuieterThanChannelsResponse
	ChannelStrengthRequest
	ChannelStrengthResponse
*/
package signals

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BusierThanChannelsRequest struct {
	Lowerbound float64 `protobuf:"fixed64,1,opt,name=lowerbound" json:"lowerbound,omitempty"`
}

func (m *BusierThanChannelsRequest) Reset()                    { *m = BusierThanChannelsRequest{} }
func (m *BusierThanChannelsRequest) String() string            { return proto.CompactTextString(m) }
func (*BusierThanChannelsRequest) ProtoMessage()               {}
func (*BusierThanChannelsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BusierThanChannelsRequest) GetLowerbound() float64 {
	if m != nil {
		return m.Lowerbound
	}
	return 0
}

type BusierThanChannelsResponse struct {
	Channels []*BusierThanChannelsResponse_Channel `protobuf:"bytes,1,rep,name=channels" json:"channels,omitempty"`
}

func (m *BusierThanChannelsResponse) Reset()                    { *m = BusierThanChannelsResponse{} }
func (m *BusierThanChannelsResponse) String() string            { return proto.CompactTextString(m) }
func (*BusierThanChannelsResponse) ProtoMessage()               {}
func (*BusierThanChannelsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BusierThanChannelsResponse) GetChannels() []*BusierThanChannelsResponse_Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type BusierThanChannelsResponse_Channel struct {
	Number   int32   `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Strength float64 `protobuf:"fixed64,2,opt,name=strength" json:"strength,omitempty"`
}

func (m *BusierThanChannelsResponse_Channel) Reset()         { *m = BusierThanChannelsResponse_Channel{} }
func (m *BusierThanChannelsResponse_Channel) String() string { return proto.CompactTextString(m) }
func (*BusierThanChannelsResponse_Channel) ProtoMessage()    {}
func (*BusierThanChannelsResponse_Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

func (m *BusierThanChannelsResponse_Channel) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BusierThanChannelsResponse_Channel) GetStrength() float64 {
	if m != nil {
		return m.Strength
	}
	return 0
}

type QuieterThanChannelsRequest struct {
	Upperbound float64 `protobuf:"fixed64,1,opt,name=upperbound" json:"upperbound,omitempty"`
}

func (m *QuieterThanChannelsRequest) Reset()                    { *m = QuieterThanChannelsRequest{} }
func (m *QuieterThanChannelsRequest) String() string            { return proto.CompactTextString(m) }
func (*QuieterThanChannelsRequest) ProtoMessage()               {}
func (*QuieterThanChannelsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QuieterThanChannelsRequest) GetUpperbound() float64 {
	if m != nil {
		return m.Upperbound
	}
	return 0
}

type QuieterThanChannelsResponse struct {
	Channels []*QuieterThanChannelsResponse_Channel `protobuf:"bytes,1,rep,name=channels" json:"channels,omitempty"`
}

func (m *QuieterThanChannelsResponse) Reset()                    { *m = QuieterThanChannelsResponse{} }
func (m *QuieterThanChannelsResponse) String() string            { return proto.CompactTextString(m) }
func (*QuieterThanChannelsResponse) ProtoMessage()               {}
func (*QuieterThanChannelsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QuieterThanChannelsResponse) GetChannels() []*QuieterThanChannelsResponse_Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type QuieterThanChannelsResponse_Channel struct {
	Number   int32   `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Strength float64 `protobuf:"fixed64,2,opt,name=strength" json:"strength,omitempty"`
}

func (m *QuieterThanChannelsResponse_Channel) Reset()         { *m = QuieterThanChannelsResponse_Channel{} }
func (m *QuieterThanChannelsResponse_Channel) String() string { return proto.CompactTextString(m) }
func (*QuieterThanChannelsResponse_Channel) ProtoMessage()    {}
func (*QuieterThanChannelsResponse_Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

func (m *QuieterThanChannelsResponse_Channel) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *QuieterThanChannelsResponse_Channel) GetStrength() float64 {
	if m != nil {
		return m.Strength
	}
	return 0
}

type ChannelStrengthRequest struct {
	Channel int32 `protobuf:"varint,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *ChannelStrengthRequest) Reset()                    { *m = ChannelStrengthRequest{} }
func (m *ChannelStrengthRequest) String() string            { return proto.CompactTextString(m) }
func (*ChannelStrengthRequest) ProtoMessage()               {}
func (*ChannelStrengthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChannelStrengthRequest) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

type ChannelStrengthResponse struct {
	Strength float64 `protobuf:"fixed64,1,opt,name=strength" json:"strength,omitempty"`
	Quality  float64 `protobuf:"fixed64,2,opt,name=quality" json:"quality,omitempty"`
}

func (m *ChannelStrengthResponse) Reset()                    { *m = ChannelStrengthResponse{} }
func (m *ChannelStrengthResponse) String() string            { return proto.CompactTextString(m) }
func (*ChannelStrengthResponse) ProtoMessage()               {}
func (*ChannelStrengthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChannelStrengthResponse) GetStrength() float64 {
	if m != nil {
		return m.Strength
	}
	return 0
}

func (m *ChannelStrengthResponse) GetQuality() float64 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func init() {
	proto.RegisterType((*BusierThanChannelsRequest)(nil), "signals.BusierThanChannelsRequest")
	proto.RegisterType((*BusierThanChannelsResponse)(nil), "signals.BusierThanChannelsResponse")
	proto.RegisterType((*BusierThanChannelsResponse_Channel)(nil), "signals.BusierThanChannelsResponse.Channel")
	proto.RegisterType((*QuieterThanChannelsRequest)(nil), "signals.QuieterThanChannelsRequest")
	proto.RegisterType((*QuieterThanChannelsResponse)(nil), "signals.QuieterThanChannelsResponse")
	proto.RegisterType((*QuieterThanChannelsResponse_Channel)(nil), "signals.QuieterThanChannelsResponse.Channel")
	proto.RegisterType((*ChannelStrengthRequest)(nil), "signals.ChannelStrengthRequest")
	proto.RegisterType((*ChannelStrengthResponse)(nil), "signals.ChannelStrengthResponse")
}

func init() { proto.RegisterFile("signals.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x14, 0x64, 0x7f, 0x3f, 0x6c, 0xcb, 0x13, 0x11, 0x56, 0xa8, 0x71, 0x05, 0x2d, 0x5b, 0x0f, 0x05,
	0xa5, 0x87, 0x78, 0x54, 0x2f, 0x7a, 0xd0, 0x9b, 0x98, 0xf6, 0x2a, 0x98, 0xd6, 0xa5, 0x0d, 0xc4,
	0x4d, 0xba, 0x7f, 0x14, 0x3d, 0xf8, 0x69, 0xc4, 0xcf, 0x29, 0xa6, 0x6f, 0x63, 0x6d, 0xb6, 0xa1,
	0x07, 0x8f, 0x33, 0x9b, 0x79, 0xf3, 0x86, 0x79, 0x81, 0x2d, 0x9d, 0x4c, 0x64, 0x9c, 0xea, 0x7e,
	0xae, 0x32, 0x93, 0xd1, 0x26, 0x42, 0x7e, 0x06, 0x7b, 0x97, 0x56, 0x27, 0x42, 0x0d, 0xa7, 0xb1,
	0xbc, 0x9a, 0xc6, 0x52, 0x8a, 0x54, 0x47, 0x62, 0x66, 0x85, 0x36, 0xf4, 0x00, 0x20, 0xcd, 0x5e,
	0x84, 0x1a, 0x65, 0x56, 0x3e, 0x06, 0xa4, 0x43, 0x7a, 0x24, 0x5a, 0x60, 0xf8, 0x07, 0x01, 0xe6,
	0x53, 0xeb, 0x3c, 0x93, 0x5a, 0xd0, 0x6b, 0x68, 0x8d, 0x91, 0x0b, 0x48, 0xe7, 0x7f, 0x6f, 0x33,
	0x3c, 0xee, 0xbb, 0x35, 0x56, 0xcb, 0xfa, 0x48, 0x44, 0xa5, 0x98, 0x5d, 0x40, 0x13, 0x49, 0xda,
	0x86, 0x86, 0xb4, 0x4f, 0x23, 0xa1, 0x8a, 0x75, 0x36, 0x22, 0x44, 0x94, 0x41, 0x4b, 0x1b, 0x25,
	0xe4, 0xc4, 0x4c, 0x83, 0x7f, 0xc5, 0xa2, 0x25, 0xe6, 0xe7, 0xc0, 0xee, 0x6c, 0x22, 0xcc, 0xca,
	0x90, 0x36, 0xcf, 0x97, 0x42, 0xfe, 0x30, 0xfc, 0x93, 0xc0, 0xbe, 0x57, 0x8e, 0x29, 0x6f, 0x2a,
	0x29, 0x4f, 0xca, 0x94, 0x35, 0xba, 0xbf, 0x8f, 0x19, 0x42, 0x1b, 0xe5, 0x03, 0xa4, 0x5c, 0xc4,
	0x00, 0x9a, 0x68, 0x82, 0xe3, 0x1c, 0xe4, 0xb7, 0xb0, 0x5b, 0xd1, 0x60, 0xae, 0x45, 0x2b, 0xf2,
	0xdb, 0xea, 0x7b, 0xe0, 0xcc, 0xc6, 0x69, 0x62, 0x5e, 0x71, 0x0b, 0x07, 0xc3, 0x37, 0xdf, 0x3d,
	0x0d, 0x84, 0x7a, 0x4e, 0xc6, 0x82, 0xde, 0x03, 0xad, 0x3e, 0x52, 0x5e, 0x7b, 0x14, 0x45, 0x02,
	0xd6, 0x5d, 0xe3, 0x70, 0xc2, 0x77, 0x6f, 0xcf, 0xce, 0xfc, 0x01, 0x76, 0x3c, 0xaf, 0xb4, 0x5b,
	0x5f, 0xd6, 0xdc, 0xfe, 0x68, 0x9d, 0x46, 0x43, 0x59, 0x29, 0xc0, 0x79, 0x0f, 0x61, 0x7b, 0xe9,
	0x85, 0x1e, 0x96, 0x23, 0xfd, 0xa5, 0xb1, 0xce, 0xea, 0x0f, 0xe6, 0x7e, 0xa3, 0x46, 0xf1, 0x2f,
	0x9f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x26, 0xaa, 0x8d, 0xfe, 0xdc, 0x03, 0x00, 0x00,
}
